version: '3.8'

services:
  merch-api:
    build: ../.
    environment:
      DatabaseConnectionOptions__ConnectionString: "Host=host.docker.internal;Port=5424;Database=merch-api;Username=postgres;Password=merch-pass"
    hostname: merchandise-api
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on: 
      - merch-api-postgres
      - stock-api
      - emailing-service
      - supply-service
      - employees-service
    
  merch-api-postgres:
    image: postgres:latest
    ports: 
      - "5424:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: merch-pass
      POSTGRES_DB: merch-api
    command: "-c log_statement=all"
    
  supply-service:
    image: ghcr.io/ozon-edu-csharp-2021/supply-service:main
    environment:
      DbConfiguration__ConnectionString: "Host=host.docker.internal;Port=5426;Database=supply-service;Username=postgres;Password=supplyServicePassword"
    hostname: supply-service
    depends_on:
      - supply-service-db
      
  emailing-service:
    image: ghcr.io/ozon-edu-csharp-2021/emailing-service:main
    hostname: emailing-service
    
  employees-service:
    image: ghcr.io/ozon-edu-csharp-2021/employees-service:main
    hostname: employees-service
    depends_on:
      - employees-service-postgres-db
    volumes:
      - ./src:/src
      
  stock-api:
    image: ghcr.io/ozon-edu-csharp-2021/stock-api:main
    hostname: stock-api
    environment:
      DatabaseConnectionOptions__ConnectionString: "Host=host.docker.internal;Port=5427;Database=stock-api;Username=postgres;Password=stockApiPassword"
    depends_on:
      - stock-api-db
      
  supply-service-db:
    image: postgres:latest
    ports:
      - "5426:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supplyServicePassword
      POSTGRES_DB: supply-service
      
  employees-service-db:
    image: postgres:latest
    ports:
      - "5425:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: employees-service
    volumes:
      - ./db/employees-service-postgres-db/dbdata:/var/lib/postgresql/data
      
  stock-api-db:
    image: postgres:latest
    ports:
      - "5427:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: stockApiPassword
      POSTGRES_DB: stock-api