version: '3.8'

services:
  merch-api:
    build: ../.
    environment:
      DatabaseConnectionOptions__ConnectionString: "Host=host.docker.internal;Port=5424;Database=merch-api;Username=postgres;Password=merch-pass"
    hostname: merchandise-api
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on: 
      - merch-api-postgres
      - stock-api
      - emailing-service
      - supply-service
      - employees-service
    
  merch-api-postgres:
    image: postgres:latest
    ports: 
      - "5424:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: merch-pass
      POSTGRES_DB: merch-api
    command: "-c log_statement=all"